parameters:
#    lahu_beanstalk.example.class: Lahu\BeanstalkBundle\Example

services:
#    lahu_beanstalk.example:
#        class: %lahu_beanstalk.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
